
project_id = "zwtfvwfluoebddezbjqe"

[functions]
  [functions.admin-settings]
    verify_jwt = false
  [functions.news-feed]
    verify_jwt = false
  [functions.gemini-api]
    verify_jwt = false
  [functions.chat-room]
    verify_jwt = false
  [functions.system-stats]
    verify_jwt = false
  [functions.track-activity]
    verify_jwt = false
    
[database]
  functions_path = "supabase/migrations"
